### PR TITLE
Updated Android tutorial for ParsePush

### PR DESCRIPTION
**Pull request by a--hoang**
###This tutorial is now in line with the instructions at:
- https://parse.com/tutorials/android-push-notifications  
- https://parse.com/docs/android/guide#push-notifications

###Summary:  
PushService is now deprecated and we should use ParsePush instead. The previous tutorial used PushService and several other **deprecated** methods (see https://parse.com/docs/android/api/deprecated-list.html ) - this demo, while simplified to pushing to channels only, uses the new standards.

In addition, the previous tutorial was built with eclipse. This tutorial was built with Android Studio (now the standard IDE for Android) and several modifications (including the .gitignore and the gradle files) have been modified to reflect Android Studio's gradle build system.

-Andrew Hoang 5/20/15

### CODE REVIEW

**Comment by a--hoang** [comment]
All set with the CLA.

**Comment by hramos** [comment]
This is great! We'll take a look. Can you email me at hector@parse.com with your t-shirt size and shipping address? We'd like to send you some swag.

**Comment by a--hoang** [comment]
Hi Hector,
I'm flattered! My t shirt is adult medium and my address is:

Andrew Hoang
20 Blueberry Path
Acton, MA 01720

Thanks for thinking of me, and please do let me know if you'd like me to
add more advanced features (targeting etc).

Best,
Andrew Hoang
a--hoang on Github

**Comment by grantland** [comment]
This looks like an awesome set of features, however, it's extremely difficult to review since it seems to combine code changes, converting to gradle, and modifying whitespace. Could you split this PR up into individual PRs for each change?

**Comment by a--hoang** [comment]
You got it. Will keep you updated.

**Comment by grantland** [comment]
This has been inactive for some time now, so I'll be closing it if it isn't updated soon. /cc @a--hoang

**Comment by a--hoang** [comment]
Been bogged down with work - will look to have updates before end of
August. Thanks Grant.
-AH
ᐧ

On Fri, Aug 14, 2015 at 8:09 PM, Grantland Chew <notifications@github.com>
wrote:

> This has been inactive for some time now, so I'll be closing it if it
> isn't updated soon. /cc @a--hoang <https://github.com/a--hoang>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ParsePlatform/PushTutorial/pull/19#issuecomment-131271036>
> .
>



-- 
Andrew Hoang
Director
BostonHacks, BU's student hackathon


Visit us at bostonhacks.io!
<http://bostonhacks.io/>

-----------------------------------------------

Boston University
College of Engineering
B.S. Computer Engineering '18 (expected)
andrewhoang.me <http://www.andrewhoang.me>
ahoang18 (at) bu.edu

[image: Inbox Status •]
<http://indicator.email/user/4e735500-d7f8-11e4-87dd-3159ecc3e261/>

**Comment by grantland** [comment]
@a--hoang friendly ping :smile:

**Comment by gfosco** [comment]
If you get around to updating this, please re-open.  Thanks!

**Comment by zhouhao27** [comment]
The new sdk doesn't work for push notification. The latest version which works is 1.9.2 as I know.

**Pull request closed without merging**
